// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['paper', 'R', 'Utils/Utils', 'Tools/Tool'], function(P, R, Utils, Tool) {
    var MoveTool;
    MoveTool = (function(superClass) {
      extend(MoveTool, superClass);

      MoveTool.label = 'Move';

      MoveTool.description = '';

      MoveTool.iconURL = 'new 1/Hand.svg';

      MoveTool.favorite = true;

      MoveTool.category = '';

      MoveTool.cursor = {
        position: {
          x: 16,
          y: 16
        },
        name: 'default',
        icon: R.style === 'line' ? 'mouse_move' : 'hand'
      };

      MoveTool.order = 0;

      function MoveTool() {
        MoveTool.__super__.constructor.call(this, true);
        this.prevPoint = {
          x: 0,
          y: 0
        };
        this.dragging = false;
        return;
      }

      MoveTool.prototype.select = function(deselectItems, updateParameters, forceSelect, selectedBy) {
        if (deselectItems == null) {
          deselectItems = false;
        }
        if (updateParameters == null) {
          updateParameters = true;
        }
        if (forceSelect == null) {
          forceSelect = false;
        }
        if (selectedBy == null) {
          selectedBy = 'default';
        }
        MoveTool.__super__.select.call(this, deselectItems, updateParameters, selectedBy);
        R.stageJ.addClass("moveTool");
      };

      MoveTool.prototype.deselect = function() {
        MoveTool.__super__.deselect.call(this);
        R.stageJ.removeClass("moveTool");
      };

      MoveTool.prototype.begin = function(event) {};

      MoveTool.prototype.update = function(event) {};

      MoveTool.prototype.end = function(moved) {};

      MoveTool.prototype.beginNative = function(event) {
        var point;
        this.dragging = true;
        point = Utils.Event.GetPoint(event);
        this.initialPosition = point;
        this.prevPoint = point;
      };

      MoveTool.prototype.updateNative = function(event) {
        var point;
        if (this.dragging) {
          point = Utils.Event.GetPoint(event);
          R.view.moveBy({
            x: (this.prevPoint.x - point.x) / P.view.zoom,
            y: (this.prevPoint.y - point.y) / P.view.zoom
          });
          this.prevPoint = point;
        }
      };

      MoveTool.prototype.endNative = function(event) {
        this.dragging = false;
      };

      return MoveTool;

    })(Tool);
    R.Tools.Move = MoveTool;
    return MoveTool;
  });

}).call(this);

//# sourceMappingURL=MoveTool.js.map
