// Generated by CoffeeScript 1.10.0
(function() {
  var baseUrl, getParameters, libs, parameters, prefix, repository;

  libs = '../../libs/';

  getParameters = function(hash) {
    var key, parameters, re, tokens, value;
    hash = hash.replace('#', '');
    parameters = {};
    re = /[?&]?([^=]+)=([^&]*)/g;
    while (tokens = re.exec(hash)) {
      key = decodeURIComponent(tokens[1]);
      value = decodeURIComponent(tokens[2]);
      parameters[key] = value === 'true' ? true : value === 'false' ? false : value;
    }
    return parameters;
  };

  parameters = typeof document !== "undefined" && document !== null ? getParameters(document.location.hash) : null;

  repository = {
    owner: 'arthursw',
    commit: null
  };

  if ((parameters != null) && (parameters['repository-owner'] != null) && (parameters['repository-commit'] != null)) {
    prefix = parameters['repository-use-cdn'] != null ? '//cdn.' : '//';
    baseUrl = prefix + 'rawgit.com/' + parameters['repository-owner'] + '/comme-un-dessein-client/' + parameters['repository-commit'] + '/js';
    repository = {
      owner: parameters['repository-owner'],
      commit: parameters['repository-commit']
    };
    libs = location.origin + '/static/libs/';
  } else {
    baseUrl = '../static/comme-un-dessein-client/js';
  }

  requirejs.config({
    waitSeconds: 300,
    baseUrl: baseUrl,
    paths: {
      'facebook': ['//connect.facebook.net/en_US/sdk'],
      'i18next': [libs + 'i18next.min'],
      'i18nextXHRBackendID': [libs + 'i18nextXHRBackend'],
      'i18nextBrowserLanguageDetectorID': [libs + 'i18nextBrowserLanguageDetector'],
      'moment': [libs + 'moment.min'],
      'jqueryI18next': [libs + 'jquery-i18next.min'],
      'hammer': [libs + 'hammer.min'],
      'underscore': [libs + 'underscore-min'],
      'jquery': [libs + 'jquery-2.1.3.min'],
      'jqueryUi': [libs + 'jquery-ui.min'],
      'mousewheel': [libs + 'jquery.mousewheel.min'],
      'scrollbar': [libs + 'jquery.mCustomScrollbar.min'],
      'tinycolor2': [libs + 'tinycolor'],
      'bootstrap': [libs + 'bootstrap.min'],
      'paper': [libs + 'paper-full'],
      'gui': [libs + 'dat.gui'],
      'zeroClipboard': [libs + 'ZeroClipboard.min'],
      'socket.ioID': libs + 'socket.io',
      'js-cookie': libs + 'js.cookie'
    },
    shim: {
      'oembed': ['jquery'],
      'mousewheel': ['jquery'],
      'scrollbar': ['jquery'],
      'jqueryUi': ['jquery'],
      'bootstrap': ['jquery'],
      'typeahead': ['jquery'],
      'js-cookie': ['jquery'],
      'jqtree': ['jquery'],
      'aceDiff': ['jquery', 'diffMatch', 'ace/ace'],
      'i18nextXHRBackend': ['i18next'],
      'i18nextBrowserLanguageDetector': ['i18next'],
      'jqueryI18next': ['i18next'],
      'colorpickersliders': {
        deps: ['jquery', 'tinycolor2']
      },
      'underscore': {
        exports: '_'
      },
      'jquery': {
        exports: '$'
      },
      'facebook': {
        exports: 'FB'
      }
    }
  });

  requirejs(['R'], function(R) {
    R.repository = repository;
    R.tipibot = parameters['tipibot'];
    R.style = parameters['style'] || 'line';
    R.initialZoom = parameters['zoom'];
    R.getParameters = getParameters;
    R.administrator = parameters['administrator'];
    requirejs(['Main']);
  });

}).call(this);
