({
    baseUrl: ".",	    
    paths: {
      // 'facebook': '//connect.facebook.net/en_US/sdk',
      'requirejs': '../../wetu-server/Wetu/static/libs/require.min',
      // 'domReady': '../../wetu-server/Wetu/static/libs/domReady',
      'i18next': '../../wetu-server/Wetu/static/libs/i18next.min',
      'i18nextXHRBackendID': '../../wetu-server/Wetu/static/libs/i18nextXHRBackend',
      'i18nextBrowserLanguageDetectorID': '../../wetu-server/Wetu/static/libs/i18nextBrowserLanguageDetector',
      'moment': '../../wetu-server/Wetu/static/libs/moment.min',
      'jqueryI18next': '../../wetu-server/Wetu/static/libs/jquery-i18next.min',
      'hammer': '../../wetu-server/Wetu/static/libs/hammer.min',
      // 'aceTools': '../../wetu-server/Wetu/static/libs/ace/ext-language_tools',
      'underscore': '../../wetu-server/Wetu/static/libs/underscore-min',
      'jquery': '../../wetu-server/Wetu/static/libs/jquery-2.1.3.min',
      'jqueryUi': '../../wetu-server/Wetu/static/libs/jquery-ui.min',
      'mousewheel': '../../wetu-server/Wetu/static/libs/jquery.mousewheel.min',
      // 'scrollbar': '../../wetu-server/Wetu/static/libs/jquery.mCustomScrollbar.min',
      'tinycolor2': '../../wetu-server/Wetu/static/libs/tinycolor',
      'bootstrap': '../../wetu-server/Wetu/static/libs/bootstrap.min',
      'paper': '../../wetu-server/Wetu/static/libs/paper-full',
      // 'three': '../../wetu-server/Wetu/static/libs/three',
      'gui': '../../wetu-server/Wetu/static/libs/dat.gui',
      // 'typeahead': '../../wetu-server/Wetu/static/libs/typeahead.bundle.min',
      // 'pinit': '../../wetu-server/Wetu/static/libs/pinit',
      // 'howler': '../../wetu-server/Wetu/static/libs/howler',
      // 'zeroClipboard': '../../wetu-server/Wetu/static/libs/ZeroClipboard.min',
      // 'diffMatch': '../../wetu-server/Wetu/static/libs/AceDiff/diff_match_patch',
      // 'aceDiff': '../../wetu-server/Wetu/static/libs/AceDiff/ace-diff',
      // 'colorpickersliders': '../../wetu-server/Wetu/static/libs/bootstrap-colorpickersliders/bootstrap.colorpickersliders.nocielch',
      // 'requestAnimationFrame': '../../wetu-server/Wetu/static/libs/RequestAnimationFrame',
      // 'coffeescript-compiler': '../../wetu-server/Wetu/static/libs/coffee-script',
      // 'tween': '../../wetu-server/Wetu/static/libs/tween.min',
      'socket.ioID': '../../wetu-server/Wetu/static/libs/socket.io',
      // 'oembed': '../../wetu-server/Wetu/static/libs/jquery.oembed',
      // 'jqtree': '../../wetu-server/Wetu/static/libs/jqtree/tree.jquery',
      'js-cookie': '../../wetu-server/Wetu/static/libs/js.cookie',
      // 'octokat': '../../wetu-server/Wetu/static/libs/octokat',
      // 'spacebrew': '../../wetu-server/Wetu/static/libs/sb-1.4.1.min',
      // 'jszip': '../../wetu-server/Wetu/static/libs/jszip/jszip',
      // 'fileSaver': '../../wetu-server/Wetu/static/libs/FileSaver.min',
      // 'color-classifier': '../../wetu-server/Wetu/static/libs/color-classifier'
    },
    shim: {
      'mousewheel': ['jquery'],
      // 'scrollbar': ['jquery'],
      'jqueryUi': ['jquery'],
      'bootstrap': ['jquery'],
      'js-cookie': ['jquery'],
      'i18nextXHRBackendID': ['i18next'],
      'i18nextBrowserLanguageDetectorID': ['i18next'],
      'jqueryI18next': ['i18next'],
      'underscore': {
        exports: '_'
      },
      'jquery': {
        exports: '$'
      }
    },
    include: ["requirejs", 
              "js-cookie", 
              "Main", 
              "View/Grid", 
              "Items/Paths/Path", 
              "Tools/MoveTool",
              "Tools/SelectTool",
              "Tools/PathTool",
              "Tools/EraserTool",
              "Tools/ItemTool"],
    name: "App",
    out: "App-built.js"
})