// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['Items/Paths/PrecisePaths/StepPath', 'Spacebrew'], function(StepPath, spacebrew) {
    var SpacePath;
    SpacePath = (function(superClass) {
      extend(SpacePath, superClass);

      function SpacePath() {
        return SpacePath.__super__.constructor.apply(this, arguments);
      }

      SpacePath.label = 'Space path';

      SpacePath.description = "This path sends coordinates to spacebrew.";

      SpacePath.iconURL = 'static/images/icons/inverted/editCurve.png';

      SpacePath.initializeParameters = function() {
        var parameters;
        parameters = SpacePath.__super__.constructor.initializeParameters.call(this);
        parameters['Spacebrew'] = {
          pause: {
            type: 'checkbox',
            label: 'Pause',
            "default": false,
            onChange: function(value) {
              var i, item, len, ref;
              ref = R.selectedItems;
              for (i = 0, len = ref.length; i < len; i++) {
                item = ref[i];
                item.data.pause = value;
              }
            }
          },
          scaleDrawing: {
            type: 'slider',
            label: 'Scale',
            min: 0,
            max: 500,
            "default": 100
          }
        };
        return parameters;
      };

      SpacePath.parameters = SpacePath.initializeParameters();

      SpacePath.createTool(SpacePath);

      SpacePath.prototype.getViewBounds = function() {
        var bounds, rectangle;
        rectangle = paper.view.bounds;
        bounds = {
          x: rectangle.x,
          y: rectangle.y,
          width: rectangle.width,
          height: rectangle.height
        };
        return bounds;
      };

      SpacePath.prototype.beginCreate = function(point, event) {
        SpacePath.__super__.beginCreate.call(this, point, event);
        if (this.data.pause) {
          return;
        }
        spacebrew.send("command", "string", JSON.stringify({
          type: 'pen',
          direction: 'down'
        }));
        spacebrew.send("command", "string", JSON.stringify({
          point: point,
          type: 'moveTo',
          bounds: this.getViewBounds(),
          scale: this.data.scaleDrawing
        }));
      };

      SpacePath.prototype.updateCreate = function(point, event) {
        SpacePath.__super__.updateCreate.call(this, point, event);
        if (this.data.pause) {
          return;
        }
        spacebrew.send("command", "string", JSON.stringify({
          point: point,
          type: 'goTo',
          bounds: this.getViewBounds(),
          scale: this.data.scaleDrawing
        }));
      };

      SpacePath.prototype.createMove = function(event) {
        SpacePath.__super__.createMove.call(this, event);
      };

      SpacePath.prototype.endCreate = function(point, event) {
        SpacePath.__super__.endCreate.call(this, point, event);
        if (this.data.pause) {
          return;
        }
        spacebrew.send("command", "string", JSON.stringify({
          type: 'pen',
          direction: 'up'
        }));
      };

      return SpacePath;

    })(StepPath);
    return SpacePath;
  });

}).call(this);
